BEGIN;


CREATE TABLE nyc_yellow_taxi_trips (trip_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                                                                vendor_id TEXT NOT NULL,
                                                                                               tpep_pickup_datetime TIMESTAMPTZ NOT NULL,
                                                                                                                                tpep_dropoff_datetime TIMESTAMPTZ NOT NULL,
                                                                                                                                                                  passenger_count INTEGER NOT NULL,
                                                                                                                                                                                          trip_distance NUMERIC(8, 2) NOT NULL,
                                                                                                                                                                                                                      pickup_longitude NUMERIC(18, 15) NOT NULL,
                                                                                                                                                                                                                                                       pickup_latitude NUMERIC(18, 15) NOT NULL,
                                                                                                                                                                                                                                                                                       rate_code_id TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                         store_and_fwd_flag TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                 dropoff_longitude NUMERIC(18, 15) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                   dropoff_latitude NUMERIC(18, 15) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                    payment_type TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      fare_amount NUMERIC(9, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                extra NUMERIC(9, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mta_tax NUMERIC(5, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tip_amount NUMERIC(9, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   tolls_amount NUMERIC(9, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              improvement_surcharge NUMERIC(9, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total_amount NUMERIC(9, 2) NOT NULL);

\copy nyc_yellow_taxi_trips (vendor_id, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code_id, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount)
FROM './data/nyc_yellow_taxi_trips.csv' WITH (FORMAT CSV,
                                              HEADER);


COMMIT;