--psql
 BEGIN;


CREATE TABLE pls_fy2018_libraries (stabr TEXT NOT NULL,
                                              fscskey TEXT CONSTRAINT fscskey_2018_pkey PRIMARY KEY,
                                                                                        libid TEXT NOT NULL,
                                                                                                   libname TEXT NOT NULL,
                                                                                                                address TEXT NOT NULL,
                                                                                                                             city TEXT NOT NULL,
                                                                                                                                       zip TEXT NOT NULL,
                                                                                                                                                county TEXT NOT NULL,
                                                                                                                                                            phone TEXT NOT NULL,
                                                                                                                                                                       c_relatn TEXT NOT NULL,
                                                                                                                                                                                     c_legbas TEXT NOT NULL,
                                                                                                                                                                                                   c_admin TEXT NOT NULL,
                                                                                                                                                                                                                c_fscs TEXT NOT NULL,
                                                                                                                                                                                                                            geocode TEXT NOT NULL,
                                                                                                                                                                                                                                         lsabound TEXT NOT NULL,
                                                                                                                                                                                                                                                       startdat TEXT NOT NULL,
                                                                                                                                                                                                                                                                     enddate TEXT NOT NULL,
                                                                                                                                                                                                                                                                                  popu_lsa INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                   popu_und INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                    centlib INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                    branlib INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                    bkmob INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                  totstaff NUMERIC(8, 2) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                         bkvol INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                       ebook INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                     audio_ph INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                      audio_dl INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       video_ph INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        video_dl INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ec_lo_ot INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subscrip INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           hrs_open INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            visits INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           reference INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             regbor INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totcir INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           kidcircl INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totpro INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           gpterms INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           pitusr INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          wifisess INTEGER NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           obereg TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       statstru TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     statname TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   stataddr TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 longitud NUMERIC(10, 7) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         latitude NUMERIC(10, 7) NOT NULL);

\copy pls_fy2018_libraries
FROM './data/pls_fy2018_libraries.csv' WITH (FORMAT CSV,
                                             HEADER);


CREATE INDEX libname_2018_idx ON pls_fy2018_libraries (libname);



COMMIT;

SELECT * FROM pls_fy2018_libraries;
